### PR TITLE
python setuptools packaging

### PR DESCRIPTION
**Pull request by riccardocagnasso**
I made this package distributable with setuptools. You should edit setup.py to add author info

### CODE REVIEW

**Comment by diovudau** [comment]
Thank you for your time and work. 
This library is intended to be copied into the source tree, not for system wide installation.

Do you see any conflicts with that principle in your changes?

For example the example files: As I see it moving them into a subdir will make them unable to find the nsmclient.

**Comment by riccardocagnasso** [comment]
You seem to import with 

`from nsmclient import NSMClient`

so it should be fine. Maybe you should do a bit of rewriting on test-importresources.py

**Comment by diovudau** [comment]
So, what is the benefit for this library having setuptools?

**Comment by riccardocagnasso** [comment]
Welll I, uhm... WHAT?

Are you asking what is the benefit in having a library distributed as a separate package?

I'd say "many". Mainly the ability to upgrade the library to a new version easily. The ability to mantain a clear sourcetree. Versioning? Pick one of the billions of reasons why software is usually structured this way.

**Comment by diovudau** [comment]
I know what setuptools are for. 
As written in the readne and also in my first reply: This is a single file library that is intended to be copied into your project. How does **that** benefit from setup tools?

**Comment by riccardocagnasso** [comment]
In that a library distributed separately is better in any way and worst in none.

**Comment by diovudau** [comment]
> In that a library distributed separately is better in any way and worst in none.

I am not discussing the scope and principal design of pynsm2 here. Is there a benefit for the current intended use?

**Comment by diovudau** [comment]
Out of scope.

**Pull request closed without merging**
